In [3]:
import torch

# 创建一个二维张量
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
impport torch
a=torch.tensor(2,1,64,64)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)

SyntaxError: invalid syntax (998489127.py, line 1)

In [8]:
import torch
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [9]:
import torch

# 创建一个张量并设置 requires_grad 为 True，以便跟踪其计算历史
x = torch.ones(2, 2, requires_grad=True)

# 对张量 x 进行操作并创建一个新的张量 y
y = x + 2

# 对张量 y 进行操作并创建一个新的张量 z
z = y * y + 3

# 计算张量 z 的均值
out = z.mean()

# 打印张量 x、y、z 和 out 的值
print(x)
print(y)
print(z)
print(out)

# 重新计算 out（张量 z 的和）
out1 = z.sum()

# 打印张量 x 的形状和梯度
print(x.shape)
print(x.grad)

with torch.no_grad():
    k = x + 1
    print(k)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)
tensor(12., grad_fn=<MeanBackward0>)


In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):  # 定义了一个名为 Net 的类，它继承自 nn.Module
    def __init__(self):  # 构造函数，3x32x32的卷积层，2x2的池化层，64个全连接层
        super(Net, self).__init__()  # 调用父类的构造函数

        # 定义网络结构
        self.conv1 = nn.Conv2d(3,6,3)  # 第一个卷积层，输入通道为3，输出通道为6，卷积核大小为3x3
        self.conv2 = nn.Conv2d(6,16,3)  # 第二个卷积层，输入通道为6，输出通道为16，卷积核大小为3x3
        self.fc1 = nn.Linear(16*28*28,512)  # 第一个全连接层，输入特征数为16*28*28，输出特征数为512
        self.fc2 = nn.Linear(512,64)  # 第二个全连接层，输入特征数为512，输出特征数为64
        self.fc3 = nn.Linear(64,10)  # 第三个全连接层，输入特征数为64，输出特征数为10

    def forward(self, x):
        # 定义前向传播过程
        x=self.conv1(x)  # 卷积层 1
        x=F.relu(x)  # 使用 ReLU 激活函数

        x=self.conv2(x)  # 卷积层 2
        x=F.relu(x)  # 使用 ReLU 激活函数

        x=x.view(-1,16*28*28)  # 对输入进行展平操作
        x=self.fc1(x)  # 全连接层 1
        x=F.relu(x)  # 使用 ReLU 激活函数

        x=self.fc2(x)  # 全连接层 2
        x=F.relu(x)  # 使用 ReLU 激活函数

        x=self.fc3(x)  # 全连接层 3
        return x  # 返回输出


net = Net()  # 创建一个名为net的神经网络实例
print(net)  # 打印神经网络实例

Net(
  (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=10, bias=True)
)


In [11]:
# 创建一个输入数据张量
input_data = torch.randn(1, 1, 32, 32)
print(input_data)
print(input_data.size())

tensor([[[[-1.1252, -0.1247,  1.8770,  ...,  0.7307, -0.7693, -0.4735],
          [ 0.6295, -2.6505,  1.2153,  ..., -0.0652, -0.1730, -0.2521],
          [-1.7594,  1.7534,  1.3731,  ...,  1.4611,  1.8640,  0.2884],
          ...,
          [-0.3907, -0.9796,  1.4657,  ..., -0.2200, -0.0878,  1.1931],
          [ 0.0375,  0.4724,  0.0144,  ..., -1.3030, -0.4801, -0.3555],
          [-0.8872,  1.1713, -0.6689,  ..., -0.9572,  1.2957, -0.9860]]]])
torch.Size([1, 1, 32, 32])


In [13]:
# 使用神经网络处理输入数据
out = net(input_data)
print(out)
print(out.size())

tensor([[-0.0419, -0.0475]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])


In [15]:
# 创建目标张量，并对其进行变形
target = torch.randn(2)
target = target.view(1, -1)
print(target)

tensor([[-0.9226,  1.4304]])


In [16]:
criterion = nn.L1Loss()  # 使用 L1 损失函数
loss = criterion(out, target)  # 计算损失值
print(loss) 

tensor(1.1793, grad_fn=<MeanBackward0>)


In [19]:
net.zero_grad()  # 清空梯度
loss.backward(retain_graph=True)  # 反向传播，并保留计算图

import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)  # 使用 SGD 优化器,学习速率为0.01
optimizer.step()  # 更新参数

out=net(input_data)  # 再次使用神经网络处理输入数据
print(out)
print(out.size())

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.